### ISSUE TITLE
Missing language-${lang} in <pre>

### ISSUE THREAD

**Issue by lask79** [oncletom/asciidoctor-prism-extension#1]
Hi Thomas,

first of all thanks for creating this plugin. I am currently trying to use it for my gatsby site. When I am trying to use some themes it seems that those themes are not rendered correctly and I found out that you are missing to return the **language-${lang}** in the  \<pre\> tag. Some of the themes like coy are making use of it to render the background.

**Example coy theme:**

```
pre[class*='language-'] > code {
  position: relative;
  border-left: 10px solid #358ccb;
  box-shadow: -1px 0px 0px 0px #358ccb, 0px 0px 0px 1px #dfdfdf;
  background-color: #fdfdfd;
  background-image: linear-gradient(
    transparent 50%,
    rgba(69, 142, 209, 0.04) 50%
  );
  background-size: 3em 3em;
  background-origin: content-box;
  background-attachment: local;
}
```

When I  change your code to this it works fine:
```
return `<pre class="highlight highlight-prismjs prismjs language-${lang}"><code class="language-${lang}" data-lang="${lang}">${node.getContent()}</code></pre>`;
````

Regards
Lasse

**Comment by thom4parisot** [comment]
Oh! Nice, I did not realise people used this module already 🙂 

Thanks for reporting this issue, I'll fix it accordingly to your proposal.
